name: Yamal Smoke and Regression Test
run-name: Testing Smoke and Regression Tests
on:
  schedule:
    # Run the smoke test every hour at the 30th minute
    - cron: '30 * * * *'
    # Run the regression test every day at midnight
    - cron: '0 0 * * *'
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
jobs:
  Run-Smoke-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Setup Chrome Browser and ChromeDriver
        run: |
          sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4
          sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add
          echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get -y update
          sudo apt-get -y install google-chrome-stable
          wget https://chromedriver.storage.googleapis.com/$(curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chown root:root /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
      - name: Run Smoke Tests
        run:  mvn test -D xmlfile=smoke-tests.xml
      - name: Upload Smoke Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Smoke Test Results HTML File
          path: target/smoke-test-report/report.html
      - name: Send Email on Failure
        if: failure()
        run: echo "Sending email notification for smoke test failure."

  Run-Regression-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Setup Chrome Browser and ChromeDriver
        run: |
          sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4
          sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add
          echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get -y update
          sudo apt-get -y install google-chrome-stable
          wget https://chromedriver.storage.googleapis.com/$(curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chown root:root /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
      - name: Run Regression Tests
        run: mvn test -D xmlfile=regression-tests.xml
      - name: Upload Regression Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Regression Test Results HTML File
          path: target/regression-test-report/report.html
      - name: Send Email on Failure
        if: failure()
        run: echo "Sending email notification for regression test failure."

  Run-Database-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Setup Chrome Browser and ChromeDriver
        run: |
          sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4
          sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add
          echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get -y update
          sudo apt-get -y install google-chrome-stable
          wget https://chromedriver.storage.googleapis.com/$(curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chown root:root /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
      - name: Run Database Tests
        run: mvn test -D cucumber.filters.tags=DB
      - name: Upload Database Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Database Test Results HTML File
          path: target/database-test-report/report.html
      - name: Send Email on Failure
        if: failure()
        run: echo "Sending email notification for database test failure."